"""Schema guards for the shipped baked quote database.

``assets/quote_database.jsonl`` is re-generated by ``bake_quote_database.py``
and is the canonical runtime input for the picker. These tests guard against
the "someone bumped :data:`bake_quote_database.BAKED_SCORE_SCHEMA_VERSION` or
reordered :data:`BAKED_SCORE_COMPONENTS` without re-baking" class of failure,
which would not surface as a test error in the baker's unit tests (those work
on freshly produced rows) but would silently demote the runtime picker to the
raw-corpus fallback path with only a stderr warning.

The bake-equivalence sweep in :mod:`test_bake_equivalence` proves baked and
raw picks agree for a freshly baked DB; these tests prove the *committed* DB
is still aligned with the current code.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

import bake_quote_database
import pick_quote

DB_PATH = Path(__file__).resolve().parent.parent / "assets" / "quote_database.jsonl"

pytestmark = pytest.mark.skipif(not DB_PATH.exists(), reason="baked quote database missing")


@pytest.fixture(scope="module")
def baked_rows() -> list[dict]:
    rows: list[dict] = []
    with DB_PATH.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


class TestBakedDbSchemaAlignment:
    def test_baker_and_picker_schema_constants_agree(self):
        # Drift between the two module-level constants is how pick-equivalence
        # silently breaks. The baked DB is stamped by the baker's constant and
        # read against the picker's — any mismatch means a fresh bake would
        # fall back to raw-corpus mode on first load.
        assert (
            bake_quote_database.BAKED_SCORE_SCHEMA_VERSION
            == pick_quote.BAKED_SCORE_SCHEMA_VERSION
        )
        assert bake_quote_database.BAKED_SCORE_COMPONENTS == pick_quote.BAKED_SCORE_COMPONENTS

    def test_committed_db_schema_version_matches_picker(self, baked_rows):
        expected = pick_quote.BAKED_SCORE_SCHEMA_VERSION
        stale = pick_quote._rows_schema_mismatch(baked_rows)
        assert stale is None, (
            f"committed baked DB has schema_version={stale!r} but picker expects "
            f"{expected}; re-run `python3 bake_quote_database.py "
            f"assets/candidates-attributed.jsonl` and commit the updated "
            f"assets/quote_database.jsonl"
        )

    def test_every_row_carries_expected_schema_version(self, baked_rows):
        expected = pick_quote.BAKED_SCORE_SCHEMA_VERSION
        bad = [
            (row.get("source_id"), row.get("line_number"), row.get("schema_version"))
            for row in baked_rows
            if row.get("schema_version") != expected
        ]
        assert not bad, f"{len(bad)} rows carry a non-expected schema_version: {bad[:5]}"

    def test_baked_score_tuple_length_matches_components(self, baked_rows):
        expected = len(pick_quote.BAKED_SCORE_COMPONENTS)
        bad = [
            (row.get("source_id"), row.get("line_number"), len(row.get("baked_score", [])))
            for row in baked_rows
            if not isinstance(row.get("baked_score"), list)
            or len(row["baked_score"]) != expected
        ]
        assert not bad, (
            f"{len(bad)} rows have baked_score length != {expected}: {bad[:5]}"
        )

    def test_every_row_has_required_baked_fields(self, baked_rows):
        required = {"baked_score", "inferred_quote_minute", "baked_rank", "schema_version"}
        for row in baked_rows:
            missing = required - set(row.keys())
            assert not missing, (
                f"baked row missing fields {missing}: "
                f"{row.get('source_id')}:{row.get('line_number')}"
            )

    def test_baked_score_components_are_integers(self, baked_rows):
        # Sorting the baked_score list as a tuple must be equivalent to sorting
        # the picker's 12-tuple at the row-intrinsic positions. If any component
        # ever bakes as a float/str the comparison semantics silently change
        # (e.g. `-0.0 < 0` rounds differently from `-0 < 0`).
        for row in baked_rows:
            score = row["baked_score"]
            for i, value in enumerate(score):
                label = pick_quote.BAKED_SCORE_COMPONENTS[i]
                assert isinstance(value, int), (
                    f"baked_score[{i}] ({label}) is {type(value).__name__}, "
                    f"expected int; row {row.get('source_id')}:{row.get('line_number')}"
                )

    def test_inferred_quote_minute_is_int_or_none(self, baked_rows):
        for row in baked_rows:
            value = row.get("inferred_quote_minute")
            assert value is None or (isinstance(value, int) and 0 <= value < 60), (
                f"inferred_quote_minute {value!r} out of range; "
                f"row {row.get('source_id')}:{row.get('line_number')}"
            )

    def test_baked_rank_is_nonnegative_int(self, baked_rows):
        for row in baked_rows:
            rank = row.get("baked_rank")
            assert isinstance(rank, int) and rank >= 0, (
                f"baked_rank {rank!r} must be non-negative int; "
                f"row {row.get('source_id')}:{row.get('line_number')}"
            )


class TestBakedDbBucketCoverage:
    def test_every_baked_row_has_valid_bucket(self, baked_rows):
        valid = pick_quote.valid_bucket_names()
        bad = [
            (row.get("source_id"), row.get("line_number"), row.get("fuzzy_bucket"))
            for row in baked_rows
            if row.get("fuzzy_bucket") not in valid
        ]
        assert not bad, (
            f"{len(bad)} baked rows have an invalid fuzzy_bucket: {bad[:5]}. "
            "Daypart-only rows must be dropped at bake time, not preserved."
        )

    def test_baked_rank_zero_indexed_contiguous_per_bucket(self, baked_rows):
        # Each bucket's baked_rank values should be 0..N-1 so the curator-UI
        # rendering is deterministic. A gap means a row was dropped after
        # ranking (shouldn't happen) or two bakes got interleaved.
        from collections import defaultdict

        per_bucket: dict[str, list[int]] = defaultdict(list)
        for row in baked_rows:
            per_bucket[row["fuzzy_bucket"]].append(row["baked_rank"])
        for bucket, ranks in per_bucket.items():
            ranks_sorted = sorted(ranks)
            expected = list(range(len(ranks_sorted)))
            assert ranks_sorted == expected, (
                f"bucket {bucket} baked_rank values not contiguous: "
                f"{ranks_sorted[:5]}... (expected 0..{len(ranks_sorted)-1})"
            )
