"""Theme modules for ``render_quote`` (issue #335).

Each theme moves here from ``_monolith`` as its own module. A theme module
imports only from the shared layers and ``themes._shared``, never from another
theme, so code two themes use lives in ``_shared``.
"""

from . import (
    alchemy,
    anna_atkins,
    atomic,
    bauhaus,
    betweenus,
    blueprint,
    carcosa,
    cartograph,
    chalkboard,
    chanbara,
    circuit,
    comic,
    deco,
    dispatch,
    fillmore,
    firmament,
    glacier,
    gothic,
    grimdark,
    grimoire,
    herbarium,
    illuminated,
    kanagawa,
    lcars,
    letter,
    marker,
    mucha,
    newsprint,
    nightvision,
    placard,
    risograph,
    roman,
    saloon,
    scholar,
    swiss,
    synoptic,
)

# Every theme module, in the order the facade (``render_quote/__init__.py``)
# searches them. A module left out is invisible to ``render_quote.X`` reads and
# patches; ``tests/test_render_quote_layering.py`` checks this against the files.
THEME_MODULES = (
    alchemy,
    anna_atkins,
    atomic,
    bauhaus,
    betweenus,
    blueprint,
    carcosa,
    cartograph,
    chalkboard,
    chanbara,
    circuit,
    comic,
    deco,
    dispatch,
    fillmore,
    firmament,
    glacier,
    gothic,
    grimdark,
    grimoire,
    herbarium,
    illuminated,
    kanagawa,
    lcars,
    letter,
    marker,
    mucha,
    newsprint,
    nightvision,
    placard,
    risograph,
    roman,
    saloon,
    scholar,
    swiss,
    synoptic,
)
