#!/usr/bin/env python3
"""Regenerate the bundled-font table in ``docs/themes.md`` from the code.

CLAUDE.md's Repo Layout used to carry a ~4,000-character hand-written
paragraph naming every directory under ``idle_hours/fonts/`` and the themes
that set type in it. Nobody could read it, and nothing kept it true (issue
#352). The table this script writes is derived instead, from two sources:

* ``THEME_FONTS``: every bundled file in any of a theme's role chains
  (``quote_regular`` / ``quote_bold`` / ``ornament`` …), fallbacks included.
* each theme module's own globals: a frame theme can load a face directly
  from a ``render_quote._paths`` constant (``lieder``'s Noto Music,
  ``expedition``'s Bebas Neue) without it ever appearing in ``THEME_FONTS``.

A bundled font directory that neither source reaches is reported as unused,
and ``--check`` fails on it, so a face cannot ship in the wheel unnoticed.

Usage::

    python3 scripts/generate_font_table.py          # rewrite the table
    python3 scripts/generate_font_table.py --check  # exit 2 if it is stale

The table sits between the ``FONT_TABLE`` markers in ``docs/themes.md``;
``tests/test_font_table.py`` runs the same check in CI.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from idle_hours.render_quote import _paths, themes  # noqa: E402
from idle_hours.render_quote.theme_tables import THEME_FONTS, THEME_ORDER  # noqa: E402

THEMES_MD = REPO_ROOT / "docs" / "themes.md"
FONTS_DIR = Path(_paths.BASE_DIR) / "fonts"
BEGIN = "<!-- FONT_TABLE:BEGIN (generated by scripts/generate_font_table.py; do not edit by hand) -->"
END = "<!-- FONT_TABLE:END -->"
# Files at the top of fonts/ rather than in a family directory.
ROOT_LABEL = "(top level)"


def _font_dir(candidate: object) -> str | None:
    """The bundled family directory a font candidate lives in, if any."""
    path = candidate[0] if isinstance(candidate, tuple) and candidate else candidate
    if not isinstance(path, str):
        return None
    try:
        rel = Path(path).resolve().relative_to(FONTS_DIR.resolve())
    except ValueError:
        return None  # a system font in the fallback chain
    return rel.parts[0] if len(rel.parts) > 1 else ROOT_LABEL


def font_usage() -> dict[str, set[str]]:
    """Map every bundled font directory to the themes that load from it."""
    usage: dict[str, set[str]] = defaultdict(set)
    for theme, roles in THEME_FONTS.items():
        for chain in roles.values():
            # The first bundled candidate is the face the theme sets; the rest
            # of the chain is fallback (Playfair backs almost every theme).
            family = next(filter(None, map(_font_dir, chain)), None)
            if family:
                usage[family].add(theme)
    for module in themes.THEME_MODULES:
        for value in vars(module).values():
            # A single face, or a (variable font, "Instance") pair. Candidate
            # *lists* imported from _paths are fallback chains, so skip them.
            if isinstance(value, str) or (isinstance(value, tuple) and len(value) == 2 and isinstance(value[1], str)):
                family = _font_dir(value)
                if family:
                    usage[family].update(module.SPEC.themes)
    return usage


def bundled_dirs() -> list[str]:
    dirs = sorted(p.name for p in FONTS_DIR.iterdir() if p.is_dir() and not p.name.startswith("__"))
    if any(p.suffix in {".ttf", ".otf"} for p in FONTS_DIR.iterdir()):
        dirs.insert(0, ROOT_LABEL)
    return dirs


def _licence(family: str) -> str:
    folder = FONTS_DIR if family == ROOT_LABEL else FONTS_DIR / family
    names = sorted(p.name for p in folder.glob("*.txt"))
    return ", ".join(names) or "—"


def render_table() -> str:
    usage = font_usage()
    order = {name: i for i, name in enumerate(THEME_ORDER)}
    rows = [
        "| Font directory | Licence | Themes that load it (in `THEME_ORDER` order) |",
        "|---|---|---|",
    ]
    for family in bundled_dirs():
        users = sorted(usage.get(family, ()), key=lambda t: order.get(t, len(order)))
        listed = ", ".join(f"`{t}`" for t in users) if users else "**unused**"
        label = "`fonts/*.ttf`" if family == ROOT_LABEL else f"`{family}/`"
        rows.append(f"| {label} | {_licence(family)} | {listed} |")
    return "\n".join([BEGIN, *rows, END])


def unused_dirs() -> list[str]:
    usage = font_usage()
    return [family for family in bundled_dirs() if not usage.get(family)]


def _splice(text: str, table: str) -> str:
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < start:
        raise SystemExit(f"{THEMES_MD}: the FONT_TABLE markers are missing")
    return text[:start] + table + text[end + len(END):]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 2 if the table is stale or a font is unused")
    args = parser.parse_args(argv)

    current = THEMES_MD.read_text(encoding="utf-8")
    wanted = _splice(current, render_table())
    unused = unused_dirs()
    if args.check:
        problems = []
        if wanted != current:
            problems.append("the font table in docs/themes.md is stale; run scripts/generate_font_table.py")
        if unused:
            problems.append(f"bundled font directories no theme loads: {unused}")
        for problem in problems:
            print(problem, file=sys.stderr)
        return 2 if problems else 0
    if wanted != current:
        THEMES_MD.write_text(wanted, encoding="utf-8")
        print(f"rewrote the font table in {THEMES_MD.relative_to(REPO_ROOT)}")
    if unused:
        print(f"warning: bundled font directories no theme loads: {unused}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
