#!/usr/bin/env python3
"""Regenerate the bundled-font table in ``docs/themes.md`` from the code.

CLAUDE.md's Repo Layout used to carry a ~4,000-character hand-written
paragraph naming every directory under ``idle_hours/fonts/`` and the themes
that set type in it. Nobody could read it, and nothing kept it true (issue
#352). The table this script writes is derived instead, from two sources:

* ``THEME_FONTS``: in each of a theme's role chains (``quote_regular`` /
  ``quote_bold`` / ``ornament`` …) the first bundled face is the one the theme
  sets, and any later bundled face is its fallback.
* each theme module's source: a frame theme can load a face directly from a
  ``render_quote._paths`` constant (``lieder``'s Noto Music, ``expedition``'s
  Bebas Neue) without it ever appearing in ``THEME_FONTS``. A constant at
  position 0 of a list literal, or used outside one, is a face the theme sets;
  at any later position it is a fallback.

A theme that sets a face is never also listed as falling back to it. The
top-level Playfair files are the last bundled fallback of nearly every chain,
so they are listed only where a theme sets them.

A bundled font directory that no theme loads is reported as unused, and
``--check`` fails on it, so a face cannot ship in the wheel unnoticed.

Usage::

    python3 scripts/generate_font_table.py          # rewrite the table
    python3 scripts/generate_font_table.py --check  # exit 2 if it is stale

The table sits between the ``FONT_TABLE`` markers in ``docs/themes.md``;
``tests/test_font_table.py`` runs the same check in CI.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from idle_hours.render_quote import _paths, themes  # noqa: E402
from idle_hours.render_quote.theme_tables import THEME_FONTS, THEME_ORDER  # noqa: E402

THEMES_MD = REPO_ROOT / "docs" / "themes.md"
FONTS_DIR = Path(_paths.BASE_DIR) / "fonts"
BEGIN = "<!-- FONT_TABLE:BEGIN (generated by scripts/generate_font_table.py; do not edit by hand) -->"
END = "<!-- FONT_TABLE:END -->"
# Files at the top of fonts/ rather than in a family directory.
ROOT_LABEL = "(top level)"


def _font_dir(candidate: object) -> str | None:
    """The bundled family directory a font candidate lives in, if any."""
    path = candidate[0] if isinstance(candidate, tuple) and candidate else candidate
    if not isinstance(path, str):
        return None
    try:
        rel = Path(path).resolve().relative_to(FONTS_DIR.resolve())
    except ValueError:
        return None  # a system font in the fallback chain
    return rel.parts[0] if len(rel.parts) > 1 else ROOT_LABEL


def _module_fonts(module) -> tuple[set[str], set[str]]:
    """Font directories a theme module sets, and those it only falls back to."""
    namespace = vars(module)

    def family_of(node: ast.AST) -> str | None:
        if isinstance(node, ast.Tuple) and node.elts:
            node = node.elts[0]  # (VARIABLE_FONT, "Instance")
        if isinstance(node, ast.Name):
            return _font_dir(namespace.get(node.id))
        if isinstance(node, ast.Attribute):
            return _font_dir(getattr(_paths, node.attr, None))
        return None

    tree = ast.parse(inspect.getsource(module))
    fallback_nodes: set[int] = set()
    sets: set[str] = set()
    falls_back: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.List):
            for position, element in enumerate(node.elts):
                family = family_of(element)
                if family is None:
                    continue
                (sets if position == 0 else falls_back).add(family)
                if position:
                    fallback_nodes.add(id(element))
                    if isinstance(element, ast.Tuple) and element.elts:
                        fallback_nodes.add(id(element.elts[0]))
    for node in ast.walk(tree):
        if isinstance(node, (ast.Name, ast.Attribute)) and id(node) not in fallback_nodes:
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                continue
            family = family_of(node)
            if family:
                sets.add(family)
    return sets, falls_back


def font_usage_by_role() -> tuple[dict[str, set[str]], dict[str, set[str]]]:
    """Map every bundled font directory to the themes that set it, and to those that fall back to it."""
    sets: dict[str, set[str]] = defaultdict(set)
    falls_back: dict[str, set[str]] = defaultdict(set)
    for theme, roles in THEME_FONTS.items():
        for chain in roles.values():
            families = [f for f in map(_font_dir, chain) if f]
            if families:
                sets[families[0]].add(theme)
                for family in families[1:]:
                    falls_back[family].add(theme)
    for module in themes.THEME_MODULES:
        module_sets, module_falls_back = _module_fonts(module)
        for family in module_sets:
            sets[family].update(module.SPEC.themes)
        for family in module_falls_back:
            falls_back[family].update(module.SPEC.themes)
    for family in list(falls_back):
        falls_back[family] -= sets.get(family, set())
    falls_back.pop(ROOT_LABEL, None)
    return sets, falls_back


def font_usage() -> dict[str, set[str]]:
    """Map every bundled font directory to every theme that loads from it."""
    sets, falls_back = font_usage_by_role()
    return {family: sets.get(family, set()) | falls_back.get(family, set()) for family in sets.keys() | falls_back.keys()}


def bundled_dirs() -> list[str]:
    dirs = sorted(p.name for p in FONTS_DIR.iterdir() if p.is_dir() and not p.name.startswith("__"))
    if any(p.suffix in {".ttf", ".otf"} for p in FONTS_DIR.iterdir()):
        dirs.insert(0, ROOT_LABEL)
    return dirs


def _licence(family: str) -> str:
    folder = FONTS_DIR if family == ROOT_LABEL else FONTS_DIR / family
    names = sorted(p.name for p in folder.glob("*.txt"))
    return ", ".join(names) or "—"


def render_table() -> str:
    sets, falls_back = font_usage_by_role()
    order = {name: i for i, name in enumerate(THEME_ORDER)}

    def listed(users: set[str]) -> str:
        return ", ".join(f"`{t}`" for t in sorted(users, key=lambda t: order.get(t, len(order))))

    rows = [
        "| Font directory | Licence | Sets it | Fallback only |",
        "|---|---|---|---|",
    ]
    for family in bundled_dirs():
        primary = sets.get(family, set())
        fallback = falls_back.get(family, set())
        if not primary and not fallback:
            primary_cell, fallback_cell = "**unused**", ""
        else:
            primary_cell, fallback_cell = listed(primary) or "—", listed(fallback) or "—"
        label = "`fonts/*.ttf`" if family == ROOT_LABEL else f"`{family}/`"
        rows.append(f"| {label} | {_licence(family)} | {primary_cell} | {fallback_cell} |")
    return "\n".join([BEGIN, *rows, END])


def unused_dirs() -> list[str]:
    usage = font_usage()
    return [family for family in bundled_dirs() if not usage.get(family)]


def _splice(text: str, table: str) -> str:
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < start:
        raise SystemExit(f"{THEMES_MD}: the FONT_TABLE markers are missing")
    return text[:start] + table + text[end + len(END):]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 2 if the table is stale or a font is unused")
    args = parser.parse_args(argv)

    current = THEMES_MD.read_text(encoding="utf-8")
    wanted = _splice(current, render_table())
    unused = unused_dirs()
    if args.check:
        problems = []
        if wanted != current:
            problems.append("the font table in docs/themes.md is stale; run scripts/generate_font_table.py")
        if unused:
            problems.append(f"bundled font directories no theme loads: {unused}")
        for problem in problems:
            print(problem, file=sys.stderr)
        return 2 if problems else 0
    if wanted != current:
        THEMES_MD.write_text(wanted, encoding="utf-8")
        print(f"rewrote the font table in {THEMES_MD.relative_to(REPO_ROOT)}")
    if unused:
        print(f"warning: bundled font directories no theme loads: {unused}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
